
# Docker Robesafe Group
# Javier Araluce (RobeSafe research group - University of Alcalá)

FROM ubuntu:18.04


RUN apt update && apt install -y --no-install-recommends \
    dialog apt-utils \
    sudo \
    wget \
    bash \
    git \
    gcc-8 \
    g++-8 \
    && rm -rf /var/lib/apt/lists/*

#NVIDIA Driver 460.39
RUN /bin/bash -c    'wget https://us.download.nvidia.com/XFree86/Linux-x86_64/460.39/NVIDIA-Linux-x86_64-460.39.run; \  
                    chmod +x NVIDIA-Linux-x86_64-460.39.run; \
                    ./NVIDIA-Linux-x86_64-460.39.run -s -N --no-kernel-module;\
                    rm -rf NVIDIA-Linux-x86_64-460.39.run'


ARG USER=docker_robesafe
ARG UID=1000
ARG GID=1000
# default password for user
ARG PW=robesafe23
# Option1: Using unencrypted password/ specifying password
RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | \
    chpasswd && \
    usermod -aG sudo docker_robesafe

USER docker_robesafe
WORKDIR /home/docker_robesafe


# INSTALL CARLA  

RUN sudo apt update && \ 
    sudo apt-get install software-properties-common && \
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test && \
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add - && \
    sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" && \
    sudo apt update && \
    rm -rf /var/lib/apt/lists/*


RUN sudo apt-get install build-essential clang-8 lld-8 g++-7 cmake ninja-build libvulkan1 python python-pip python-dev python3-dev python3-pip libpng-dev libtiff5-dev libjpeg-dev tzdata sed curl unzip autoconf libtool rsync libxml2-dev git && \
    pip2 install --user setuptools && \
    pip3 install --user -Iv setuptools==47.3.1 && \
    pip2 install --user distro && \
    pip3 install --user distro

RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-8/bin/clang++ 180 && \
    update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-8/bin/clang 180


RUN git clone --depth 1 -b carla https://github.com/CarlaUnreal/UnrealEngine.git ~/UnrealEngine_4.26 && \
    cd ~/UnrealEngine_4.26 && \
    ./Setup.sh && ./GenerateProjectFiles.sh && make && \
    cd ~/UnrealEngine_4.26/Engine/Binaries/Linux && ./UE4Editor


RUN sudo apt-get install aria2

RUN git clone https://github.com/carla-simulator/carla && \
    cd carla && \
    ./Update.sh && \
    export UE4_ROOT=~/UnrealEngine_4.26 && \
    make PythonAPI && \
    make launch &&  \
    make package &&  \
    make clean

