
# Docker Robesafe Group
# Javier Araluce (RobeSafe research group - University of Alcalá)

FROM ubuntu:20.04


RUN apt update && apt install -y --no-install-recommends \
    dialog apt-utils \
    sudo \
    wget \
    bash \
    git \
    gcc-8 \
    g++-8 \
    && rm -rf /var/lib/apt/lists/*

#NVIDIDA Driver 440.100
RUN /bin/bash -c    'wget -q https://us.download.nvidia.com/XFree86/Linux-x86_64/440.100/NVIDIA-Linux-x86_64-440.100.run; \  
                    chmod +x NVIDIA-Linux-x86_64-440.100.run; \
                    ./NVIDIA-Linux-x86_64-440.100.run -s -N --no-kernel-module;\
                    rm -rf NVIDIA-Linux-x86_64-440.100.run'


ARG USER=docker_robesafe
ARG UID=1000
ARG GID=1000
# default password for user
ARG PW=robesafe23
# Option1: Using unencrypted password/ specifying password
RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | \
    chpasswd && \
    usermod -aG sudo docker_robesafe

