
# Docker Robesafe Group
# Javier Araluce (RobeSafe research group - University of Alcalá)

FROM ubuntu:20.04


RUN apt update && apt install -y --no-install-recommends \
    dialog apt-utils \
    sudo \
    wget \
    bash \
    git \
    gcc-8 \
    g++-8 \
    && rm -rf /var/lib/apt/lists/*

#NVIDIDA Driver 460.39
RUN /bin/bash -c    'wget https://us.download.nvidia.com/XFree86/Linux-x86_64/460.39/NVIDIA-Linux-x86_64-460.39.run; \  
                    chmod +x NVIDIA-Linux-x86_64-460.39.run; \
                    ./NVIDIA-Linux-x86_64-460.39.run -s -N --no-kernel-module;\
                    rm -rf NVIDIA-Linux-x86_64-460.39.run'


ARG USER=docker_robesafe
ARG UID=1000
ARG GID=1000
# default password for user
ARG PW=robesafe23
# Option1: Using unencrypted password/ specifying password
RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | \
    chpasswd && \
    usermod -aG sudo docker_robesafe

USER docker_robesafe
WORKDIR /home/docker_robesafe

RUN apt-get update &&
sudo apt-get install software-properties-common &&
sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - &&
sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" &&
sudo apt-get update

